// GENERATED by wallust from ~/.config/wallust/templates/quickshell-theme.qml - do not edit the output
import QtQuick

pragma Singleton

QtObject {
    // Colors (from the wallpaper)
    readonly property color background: "{{background}}"
    readonly property color barBackground: "#bb{{background | strip}}"   // semi-transparent

    readonly property color accent: "{{color4}}"
    readonly property color text: "{{foreground}}"
    readonly property color inactiveWorkspace: "{{color8}}"
    readonly property color activeWorkspace: "{{foreground}}"

    // Spacing & Sizing
    readonly property int bubbleHeight: 30
    readonly property int padding: 8
    readonly property int fontSize: 13

    // Text properties
    readonly property int textSize: 20
    readonly property string fontFamily: "sans-serif"   // <- put your font here

    readonly property int gapSize: 5
    readonly property int barPadding: 8
    readonly property int barHeight: 26
    readonly property int verticalMargin: 8
    readonly property int sideMargin: 10
    readonly property int bubbleSpacing: 12

    readonly property color debugColor: "transparent"
}
