// GENERATED by wallust from ~/.config/wallust/templates/quickshell-theme.qml - do not edit the output
pragma Singleton
import QtQuick

QtObject {
    // Colors (from the wallpaper)
    readonly property color background: "#171207"
    readonly property color barBackground: "#bb171207"   // semi-transparent

    // accent: wallust's color4, but never darker than this lightness (0 = black, 1 = white)
    readonly property real minAccentLightness: 0.65
    readonly property color accentRaw: "#8D644F"
    readonly property color accent: Qt.hsla(Math.max(0, accentRaw.hslHue), accentRaw.hslSaturation, Math.max(accentRaw.hslLightness, minAccentLightness), 1.0)
    readonly property color text: "#BEBD98"
    readonly property color inactiveWorkspace: "#737252"
    readonly property color activeWorkspace: "#BEBD98"

    // Spacing & Sizing
    readonly property int bubbleHeight: 30
    readonly property int padding: 8
    readonly property int fontSize: 13

    // Text properties
    readonly property int textSize: 20
    readonly property string fontFamily: "sans-serif"   // <- put your font here

    readonly property int gapSize: 5
    readonly property int barPadding: 8
    readonly property int barHeight: 26
    readonly property int verticalMargin: 8
    readonly property int sideMargin: 10
    readonly property int bubbleSpacing: 12

    readonly property color debugColor: "transparent"
}
