### MangoHUD Configuration
legacy_layout=0

# Position and Appearance
position=top-left
round_corners=10
background_alpha=0.5
font_size=24

# CPU Metrics
cpu_stats
#cpu_temp
#cpu_power
#cpu_mhz

# GPU Metrics
gpu_stats
#gpu_temp
#gpu_core_clock
#gpu_power

# RAM & VRAM
ram
vram

# Performance & Frame Times
fps
frametime
frame_timing=1

# Battery (uncomment if using a laptop)
# battery

# Toggle Shortcuts (Shift_L + F12 to show/hide)
toggle_hud=F8
