general {
    grace = 0
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = /home/levi/.cache/wallpaper/current_symlink  # Oder leer lassen für Farb-Fallback
    color = rgb(2, 62, 63)
    blur_passes = 2                        # Weichzeichner-Durchläufe (0 = aus)
    blur_size = 7
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33                       # Größe der Passwortpunkte
    dots_spacing = 0.15                    # Abstand der Punkte
    fade_on_empty = false
    placeholder_text = <i>Passwort eingeben...</i>
}

# Uhrzeit-Anzeige
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +'%H:%M') </big></b>"
    color = rgba(255, 255, 255, 0.9)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}
