# Wallust Kitty Template

# --- THE FIXED BACKGROUND ---
# This ensures your background is ALWAYS #2f2f2f regardless of the wallpaper
background #2f2f2f
background_opacity 0.60

# --- THE TEXT (Foreground) ---
# Use color7 (usually a bright grey/white) so it's always readable
foreground #ffffff

# --- THE ACCENTS (The 16 colors) ---
# These will still change based on your wallpaper for syntax highlighting
color0  #091520
color1  #091520
color2  #635339
color3  #899096
color4  #291E18
color5  #A07D5B
color6  #55150B
color7  #BD6454
color8  #8B3D30

# Input text Color
color9  #e0e0e0

color10 #635339
color11 #899096
color12 #291E18
color13 #A07D5B
color14 #55150B
color15 #D5A9A1

# Selection colors
selection_foreground #0C1419
selection_background #BD6454

# Cursor
cursor #BD6454